name: Create release PR

on:
  push:
    branches:
      - main

jobs:

  # Pre-jobs add here... for example deploy to test env

  # Make release PR
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.releases_created }}
      version: ${{ steps.release-please.outputs.major }}.${{ steps.release-please.outputs.minor }}.${{ steps.release-please.outputs.patch }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          target-branch: ${{ github.ref_name }}

  # Here we can do anything with merged release PR... for example deploy to stage or production and etc.
  post-release-branch-merge-job:
    needs: [release-please]
    # Check if we merged our release PR
    if: needs.release-please.outputs.release_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to prod environment
        run: echo "Merged to release branch and deployed to production!"